name = "pleb-underground-sync"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
crons = ["*/5 * * * *"]

[[kv_namespaces]]
binding = "PU_STATE"
id = "03333dfe43084a0d8831ddd121d6ca64"
